version: '3'

services:
  php-fpm:
    build:
      context: ./infrastructure/php-fpm
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www

  nginx:
    build:
      context: ./infrastructure/nginx
    volumes:
      - ./:/var/www
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/sites/:/etc/nginx/sites-available
      - ./infrastructure/nginx/conf.d/:/etc/nginx/conf.d
      - ./infrastructure/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"